# Generated by Django 3.1.1 on 2020-09-28 17:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200928_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
