# Generated by Django 3.1.1 on 2020-11-27 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20201127_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='image',
            name='body',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='01', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
