# Generated by Django 3.1.1 on 2020-11-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201129_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='original_image',
            new_name='image',
        ),
    ]
