# Generated by Django 3.0.8 on 2020-12-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201203_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default='Unsorted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Album'),
        ),
    ]
