# Generated by Django 3.1.1 on 2021-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201226_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
